language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
before_install:
  - sudo service memcached stop || true
  - sudo service couchdb stop || true
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install docker-engine
  - pip install --user codecov
  - env
  # Pre-fetch docker images - seems to need to be done before docker env vars are set
  - docker pull couchbase/server:latest
  # Update env vars required by testcontainers
  - export DOCKER_HOST=tcp://127.0.0.1:2375
  - export DOCKER_TLS_VERIFY=0
  - env

cache:
  directories:
    - '$HOME/.m2/repository'
after_success:
  - codecov

